FORMAT: 1A
HOST: http://architectural-decisions.herokuapp.com

# TestAPI
Notes API is a *short texts saving* service similar to its physical paper presence on your table.

# User
This section containts all the methods for manipulating a user profile. **To be continued**

## Signup [/api/v1/signup]

### Create a new user [POST]
+ Request (application/json)

        { "user": { "name": "Chair", "email": "chair@chair.com", "password": "password", "password_confirmation": "password" } }

+ Response 201 (application/json)

        { "id": 3, "title": "Buy cheese and bread for breakfast." }

## Authentication [/api/v1/signin]
Use this resource in order to login or logout from the API.

### Create a new session - Login [POST]
In order to access resources from this API you will need firstly to create a
session. In order to be able to create a session you previously should have
signed up.After sining up, use this resource by submitting the email and the
password that you have user for signing up. The API will provide you an 
access token which will have to be sent with each request.
+ Request (application/json)

        { "session": { "email": "chair@chair.com", "password": "password" } }
    
+ Response 200 (application/json)
    + Body

            { "id": 2, "title": "Pick-up posters from post-office" }

### Destroy a session - Logout [DELETE]
Use this resource for distroying a session.
+ Response 204

